import tourList1 from '../assets/tour-list/tour-list1.jpg';
import { FaHeart, FaHome } from 'react-icons/fa';
import { PiGlobeStandFill } from 'react-icons/pi';
import { CgShapeZigzag } from 'react-icons/cg';

export const popularTourData = [
  {
    image: tourList1,
    title: 'The Grand Canyon Adventure',
    MRP: '2000',
    price: '1800',
    rating: '8.5',
    description: 'Experience the majestic beauty of the Grand Canyon with expert guides.',
    time: 7,
    user: '10',
    date: '2024-06-15',
    type: {
      name1: 'Romantic',
      icon1: FaHeart,
      name2: 'Exotic',
      icon2: PiGlobeStandFill,
    },
  },
  {
    image: tourList1,
    title: 'Mediterranean Cruise',
    MRP: '3000',
    price: '2700',
    rating: '9.2',
    description: 'Explore the wonders of the Mediterranean on this luxurious cruise.',
    time: 10,
    user: '200',
    date: '2024-07-01',
    type: {
      name1: 'Romantic',
      icon1: FaHeart,
      name2: 'Exotic',
      icon2: PiGlobeStandFill,
    },
  },
  {
    image: tourList1,
    title: 'Alaskan Wilderness Expedition',
    MRP: '2500',
    price: '2200',
    rating: '8.8',
    description: 'Journey through the wilds of Alaska on this once-in-a-lifetime expedition.',
    time: 12,
    user: '15',
    date: '2024-08-10',
    type: {
      name1: 'Romantic',
      icon1: FaHeart,
      name2: 'Exotic',
      icon2: PiGlobeStandFill,
    },
  },
  {
    image: tourList1,
    title: 'Parisian Romance Tour',
    MRP: '3500',
    price: '3200',
    rating: '9.4',
    description: 'Discover the charm and romance of Paris on this exclusive tour.',
    time: 5,
    user: '50',
    date: '2024-05-20',
    type: {
      name1: 'Romantic',
      icon1: FaHeart,
      name2: 'Exotic',
      icon2: PiGlobeStandFill,
    },
  },
  {
    image: tourList1,
    title: 'African Safari Adventure',
    MRP: '4500',
    price: '4000',
    rating: '9.0',
    description: 'Get up close with Africa’s incredible wildlife on this thrilling safari.',
    time: 14,
    user: '25',
    date: '2024-09-05',
    type: {
      name1: 'Romantic',
      icon1: FaHeart,
      name2: 'Exotic',
      icon2: PiGlobeStandFill,
    },
  },
  {
    image: tourList1,
    title: 'Bali Beach Retreat',
    MRP: '1500',
    price: '1300',
    rating: '7.5',
    description: 'Relax and unwind on the beautiful beaches of Bali.',
    time: 10,
    user: '8',
    date: '2024-10-18',
    type: {
      name1: 'Romantic',
      icon1: FaHeart,
      name2: 'Exotic',
      icon2: PiGlobeStandFill,
    },
  },
  {
    image: tourList1,
    title: 'Japan Cherry Blossom Tour',
    MRP: '4000',
    price: '3800',
    rating: '9.6',
    description: 'Experience Japan’s iconic cherry blossom season with expert local guides.',
    time: 7,
    user: '12',
    date: '2024-04-02',
    type: {
      name1: 'Romantic',
      icon1: FaHeart,
      name2: 'Exotic',
      icon2: PiGlobeStandFill,
    },
  },
  {
    image: tourList1,
    title: 'New Zealand Adventure',
    MRP: '5000',
    price: '4500',
    rating: '9.1',
    description: 'Explore the rugged beauty of New Zealand on this action-packed adventure.',
    time: 10,
    user: '20',
    date: '2024-12-12',
    type: {
      name1: 'Romantic',
      icon1: FaHeart,
      name2: 'Exotic',
      icon2: PiGlobeStandFill,
    },
  },
  {
    image: tourList1,
    title: 'Hawaiian Island Hopping',
    MRP: '2800',
    price: '2500',
    rating: '8.7',
    description: 'Hop between the Hawaiian Islands for a tropical getaway.',
    time: 7,
    user: '30',
    date: '2024-11-10',
    type: {
      name1: 'Romantic',
      icon1: FaHeart,
      name2: 'Exotic',
      icon2: PiGlobeStandFill,
    },
  },
  {
    image: tourList1,
    title: 'Rome Historical Tour',
    MRP: '1800',
    price: '1600',
    rating: '8.0',
    description: 'Discover the rich history of Rome with expert guides.',
    time: 6,
    user: '15',
    date: '2024-03-25',
    type: {
      name1: 'Romantic',
      icon1: FaHeart,
      name2: 'Exotic',
      icon2: PiGlobeStandFill,
    },
  },
];
